yaml
name: RDP via Ngrok
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Set up job
      run: echo "Setting up..."
    - name: Ngrok ডাউনলোড ও আনজিপ করুন
      run: |
        Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
        Expand-Archive -Path "ngrok.zip" -DestinationPath "."

    - name: Ngrok অথেন্টিকেশন
      run: .\ngrok.exe authtoken Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN:{{ secrets.NGROK_AUTH_TOKEN }}

    - name: RDP টানেল চালু করুন
      run: Start-Process -NoNewWindow -FilePath ".\ngrok.exe" -ArgumentList "tcp 3389"

    - name: ইউজারনেম ও পাসওয়ার্ড দেখান
      run: |
        net user runneradmin
        echo "IP:PORT Ngrok থেকে নিন এবং Remote Desktop অ্যাপে ব্যবহার করুন"

    - name: ৬ ঘণ্টা অপেক্ষা করুন
      run: Start-Sleep -Seconds 21600
