name: Deploy Telegram Bot

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Or your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update && sudo apt-get install -y jq # Install jq for parsing JSON

    - name: Install ngrok
      run: |
        # Download ngrok zip file
        curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
        
        # Unzip ngrok.zip. The -o option overwrites existing files without prompting.
        unzip -o ngrok.zip
        
        # Check if ngrok was unzipped into a subdirectory (e.g., ngrok-stable-linux-amd64/)
        # If so, move the ngrok executable to the current directory
        if [ -f "ngrok-stable-linux-amd64/ngrok" ]; then
          mv ngrok-stable-linux-amd64/ngrok .
          rm -rf ngrok-stable-linux-amd64 # Clean up the empty directory
        fi
        
        # Verify that the ngrok executable is now in the current directory
        if [ ! -f "ngrok" ]; then
          echo "Error: ngrok executable not found after unzipping or moving."
          exit 1
        fi
        
        # Make the ngrok executable runnable
        chmod +x ngrok
        
        echo "ngrok installation complete."

    - name: Configure ngrok authtoken
      run: |
        # Create the .ngrok2 directory in the home directory
        mkdir -p ~/.ngrok2
        # Write the authtoken to the ngrok.yml configuration file
        echo "authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}" > ~/.ngrok2/ngrok.yml
        echo "Ngrok authtoken configured in ~/.ngrok2/ngrok.yml"

    - name: Start Bot with Ngrok
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        PORT: 8000 # Default port for webhook, can be configured in app.py or here
      run: |
        # Run the start_bot.sh script from the current working directory
        # The script will now find ngrok in the current directory and use the configured authtoken
        bash start_bot.sh
